---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: terminal
  namespace: terminal
spec:
  serviceAccountName: terminal
  chart:
    spec:
      chart: terminal
      version: '0.4'
      sourceRef:
        kind: GitRepository
        name: okteto-charts
  interval: 15m0s
  releaseName: terminal
  values:
    ingress:
      enabled: false
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: "0.5"
        memory: 1Gi
