apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webhook-receiver
  namespace: flux-system
  annotations:
    kubernetes.io/ingress.class: "nginx"
   # cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  rules:
  - host: webhook.hephy.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: notification-webhook
            port:
              number: 9292
  tls:
  - hosts:
    - webhook.hephy.dev
    secretName: webhook-hephy-dev-tls
