apiVersion: v1
data:
    address: ENC[AES256_GCM,data:+Bs4tsj+4BxXcwvnX7ab0L/g9HJLYcciw7uriDsukSPj8OLtzSd4Pb4lUaevP0NtwDPaMaJXsQcs01IlvsIs06vr1k2XzzAt0RPiP6XFaZxrxYmvaY2EBku6Y0SAu9Aw3s8ZQUr1vnZr3WjH,iv:dExTir0ea/BePTMg5CO+rpUsNABAAKPQ+9mXVCmtQvw=,tag:CgfwezwpSzsViUJP1mRqFQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: slack-url
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-01T20:50:42Z"
    mac: ENC[AES256_GCM,data:x8zJRs+MqzJNLug8V5NnhrvUEB+aQieBdNNfFTnDWk0L0/ZnhshdSlkcLld8euW2LfBAdGany2b4jn+fHeV1pqm6FRccwusyaxDqb5atlXQaRIJFrNnzumvOp1eDn2pp4zBBnHPneekwe9duMfsQvu/2cVJ44seDEXpxPI9Xut0=,iv:DhqaocDVG9onAbmjak7UXdmpqoAUx6EDi5POO/Ijq8g=,tag:uKe6ej2UaEgagZesELPQ9Q==,type:str]
    pgp:
        - created_at: "2021-05-01T20:50:40Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA078UwqRrbaaAQ/+IaP0TWBF2PRG4PsBL2Ui+HI8/I/1Q9E+ommdWYeia95w
            uxjQPHFzAHNxqAYCMInQ/KhY7yxgz2RN8bs2SbCfFWcVh1twoQGqNqD3HhGbLUHS
            DzJTmYDa1BMb5U4TxR2rFm6yxPEoM8JvcP8c0fgsyfOc3uuxYGdFOJeLST0rDXjG
            XAQnbjN9NFb0TpOw+ENT8D09hHkGdd2f6B8mwiLqWVGKWfhDPMSriGdoyn5lgRz8
            6My0MS4xyQmdNYcWkDjTIeRuUd4ZfTMBokrv2AqkoLsDt4+Moc0zIwZkRSdux8b5
            wgECOxtt2KML209kbvp+KihX6y0mrgQZtUT++2SXus8pW7D4+ILUruLihm37Fn7P
            0WAJvuldcR3DdhsbFoNI1whKQvTmtKUI0twep7nRY9SvZ3K5f2nD3MHWlqdhmwKa
            aXPVaPbpRSCw0H53/BMs2ue5W8QL7kX8tmeYdE8TDUxE/m8Y+dcM2sQjmIpm6OE1
            Du19fY4gCcnu5rvG5osQ4WR9CpXEBbt3AKeLHkRRiryfvLx73swJvXOVCacNjps5
            C9NE6Mn/NcWylUnEJi/c5CDTtyErkAf4if5vkgB4wNCqvT576Q5TUQ3ijMF5m0G+
            MrJXRItLFR3w9Pt8FtvzACFGD7Kyz3vB/sI6KsCkYxS1ipcn5/roxPHQywk31E3U
            aAEJAhUUBxC1EF8Rma18dTNnRd56wS8hYXBuaimBimZpdubGW7BqAeCRA6h6KmPI
            je7rAOX4R6IefXewzAdNrWxQeewWRRkHnwdlJRAzqN+zy/ieG0vN0jW2PPhVRgFl
            CgEnizop7kVL
            =89/H
            -----END PGP MESSAGE-----
          fp: 61638443D4403F16D6290C391BEA1B1A6CD0DBEC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
