apiVersion: v1
data:
    token: ENC[AES256_GCM,data:6qrCxe/A7azg25Tm3/KUeoU7AmQve4db2ASrMckCTVrPMqOKfW9KGtcvKy10ZFDXlGU3fr4kDh4=,iv:NqhCgq33JG2t/oiKSfvO0vEU/AZTLh9YPO+giMptIZE=,tag:HzWvw5avGU9LhbpbEQ2Qmg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: webhook-token
    namespace: terminal
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-02T02:21:45Z"
    mac: ENC[AES256_GCM,data:nt/lbDfz08jzJlZY6m+V0XYOmNFpdgjgy9vtw5d4R7fOmsZI9BfPNttnl+z7hhW6sJAqfR98HNkb6DHUYFUeTd7ppg86XS6HVoRp8KbAXRTOkoBWLkKCZ4jmfMfPBRYx8H3bRQJsHv5y7kwRdQ4aywGMGihCxHtXTpgqlBHh+uI=,iv:ROLlVC3SYw9Y5n4UheeUV5Putqqkf6B0IsfHdCjagWE=,tag:WM035Qh+1YB5+SNmuhkJ0w==,type:str]
    pgp:
        - created_at: "2021-05-02T02:21:44Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA078UwqRrbaaAQ//fMFzu6aNMr4/HPDDd9kK35GyC4ghqUspDp1ADMRQc7Ej
            DmtDx1QvJxXIkxgCRIECKrqXdAL2yu2+cn3+rO/r903xlbqLjGpr014X1DCH+PQZ
            wE9zIycACvwGjG56lUzepufa7xlIiBY3kRuKU3Gygm9GjgvupHuVyAwT6BZ2X9Ss
            mqXY0vGY9IMthUEsr35dNVgQwga46IS6m6Bsd5APDj2GPQ4v9Hf3ai2sMmXq8Qm2
            375zbwmqKPpmrocKMR3ZgZpBFIisV7NAZindJQujlM+jGjLoCcxXQ0TgjljRyPKa
            U31Fjf6dM47aywxVPNSkjfhsVXyiKOd7fbhtxSLODak0B3jLRXVm8geqTzW+phr9
            O6MZB7Qa4WnuYirsSVN2DmxKIm8Z9QOT/0tTUFPpNMM0aSJRYPBt7IF00x2Stsbx
            /WNPa0mbmgVaNb6bteeOEHSNTlM79fdBpQEFx9XtAPmNo4DC5Bc+TiPxZ2bW6ANI
            hnIYlwTPFm0FngGPopzb/7dl+iepP3ppSOJha2k4xpcF1o8Ff8DC6j3LJIglkSFY
            NIi1xWEm6SxBLOPH/8FNtSvDb9niDfXnl+R5DCGs2sVkBR5zEao4eam6bJ0SeP5V
            0aYXHHBDIeBzR81uu8pUWdCkWvPRAieLx2mIReTe25+48Bw/s52s1qW/1iSaAJXU
            aAEJAhUvVlJd7aPQGgPtrSgc1fD/kaU7oAYqUzyRFttzMBM2w1ynR3ca1mPQ0Unq
            UVnTyQwsF8hFO2toPrtJ9gXoH1OcoMUbO5KyH7YM2S9leHTdMkM7NI6FLfXMyecD
            oc8zpC7pWDKc
            =0yeZ
            -----END PGP MESSAGE-----
          fp: 61638443D4403F16D6290C391BEA1B1A6CD0DBEC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
