apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  dependsOn:
    - name: kyverno-policies
    #- name: cert-issuers
    - name: my-secrets
    - name: ingress-nginx
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./tenants/my-cluster
  prune: true
  validation: client
