---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: wordpress-sync
  name: wordpress

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: wordpress-sync
  name: wordpress-sync
  namespace: wordpress

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: wordpress-sync
  name: wordpress-sync-reconciler
  namespace: wordpress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:wordpress:reconciler
- kind: ServiceAccount
  name: wordpress-sync
  namespace: wordpress

