name: test

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup tools
        uses: ./.github/actions/tools
      - name: Validate manifests
        run: ./scripts/validate.sh
