---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: '3.29.0'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  interval: 15m0s
  install:
    createNamespace: true
  targetNamespace: ingress-nginx
  releaseName: nginx
